### ISSUE TITLE
Account Suspended

### ISSUE THREAD

**Issue by 1davidmichael** [adilosa/awswhatsnew#8] opened 2022-03-11 19:55 UTC
I am unsure what happened but it looks like the [@awswhatsnew](https://twitter.com/awswhatsnew) twitter account has been suspended. It was pretty valuable so I was hoping to get some insight into what happened to re-open it or at least stand up a similar service.

**Comment by codestart** [comment] 2022-03-12 11:32
Hey really sorry to hear that. I've been suspended twice @AWSBlogUnreal and it can be 3 months to get back if they don't undo straight away. You do have to convince them you've fixed the problem for that to happen though. If you tell them to undo and the problem is still there, you're definitely in for 3 months outage.

The trick to not being suspended IMHO is to have logging sending you an email every time something goes wrong. Both times I was suspended I was getting an error and didn't fix it in time, but my logging wasn't even outputting the error so I just wasn't aware.

A good place to go if you want sympathy is https://twittercommunity.com and do a search for "suspended". You'll be in good company there!

I presume you've looked here:
https://developer.twitter.com/en/docs/twitter-api/v1/rate-limits

**Comment by adilosa** [comment] 2022-05-17 18:46
Hey all, yeah unfortunately this account was suspended. I am trying to appeal it with Twitter to see if I can get it unbanned. 

Thanks codestart for the tips, I'll check those out. In this case, the automated email says:

> Your account has been suspended for violation(s) of Twitter’s rules, specifically our policy regarding parody, newsfeed, commentary, and fan accounts.

Based on the policy (https://help.twitter.com/en/rules-and-policies/parody-account-policy), I don't believe the account is in error. Or at least it should be trivial to bring in line if they give me the chance.

**Comment by codestart** [comment] 2022-05-17 18:57
I got something similar before they would allow me have the account I use as Production.I had to change the name (AWS Blog Unofficial), twitter handle ***@***.***), and logo (see logo!), to be extremely obvious that it was not an official AWS account.Always wondered how you got away with it! 
-------- Original message --------From: Andrew DiLosa ***@***.***> Date: 17/05/2022  19:47  (GMT+00:00) To: adilosa/awswhatsnew ***@***.***> Cc: codestart ***@***.***>, Comment ***@***.***> Subject: Re: [adilosa/awswhatsnew] Account Suspended (Issue #8) 

Hey all, yeah unfortunately this account was suspended. I am trying to appeal it with Twitter to see if I can get it unbanned.

Thanks codestart for the tips, I'll check those out. In this case, the automated email says:



Your account has been suspended for violation(s) of Twitter’s rules, specifically our policy regarding parody, newsfeed, commentary, and fan accounts.



Based on the policy (https://help.twitter.com/en/rules-and-policies/parody-account-policy), I don't believe the account is in error. Or at least it should be trivial to bring in line if they give me the chance.

**Comment by adilosa** [comment] 2022-05-17 19:59
Yeah, I think you're right. I guess I set those like 5 years ago when there were no followers, and it just wasn't ever an issue until it was. 😅

I tried to appeal to the bots again, and submitted a post on twittercommunity.com - hopefully can restore the account. If not, maybe can make a new one?

**Comment by adilosa** [comment] 2022-05-18 20:33
Good news!! I finally got the account unsuspended and am updating everything to comply with the rules, and make sure everything still works. Should be back!

**Comment by codestart** [comment] 2022-05-18 21:54
Excellent. Look forward to my first update! 
-------- Original message --------From: Andrew DiLosa ***@***.***> Date: 18/05/2022  21:34  (GMT+00:00) To: adilosa/awswhatsnew ***@***.***> Cc: codestart ***@***.***>, Comment ***@***.***> Subject: Re: [adilosa/awswhatsnew] Account Suspended (Issue #8) 
Good news!! I finally got the account unsuspended and am updating everything to comply with the rules, and make sure everything still works. Should be back!

**Comment by adilosa** [comment] 2022-05-19 00:03
The tweets have been going all day! Closing this, happily

**Closed as completed by adilosa** 2022-05-19 00:03 UTC
